# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/market_profiles', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # MarketProfile. As you add validations to MarketProfile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      MarketProfile.create! valid_attributes
      get market_profiles_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      market_profile = MarketProfile.create! valid_attributes
      get market_profile_url(market_profile)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_market_profile_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      market_profile = MarketProfile.create! valid_attributes
      get edit_market_profile_url(market_profile)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new MarketProfile' do
        expect do
          post market_profiles_url, params: { market_profile: valid_attributes }
        end.to change(MarketProfile, :count).by(1)
      end

      it 'redirects to the created market_profile' do
        post market_profiles_url, params: { market_profile: valid_attributes }
        expect(response).to redirect_to(market_profile_url(MarketProfile.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new MarketProfile' do
        expect do
          post market_profiles_url, params: { market_profile: invalid_attributes }
        end.not_to change(MarketProfile, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post market_profiles_url, params: { market_profile: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested market_profile' do
        market_profile = MarketProfile.create! valid_attributes
        patch market_profile_url(market_profile), params: { market_profile: new_attributes }
        market_profile.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the market_profile' do
        market_profile = MarketProfile.create! valid_attributes
        patch market_profile_url(market_profile), params: { market_profile: new_attributes }
        market_profile.reload
        expect(response).to redirect_to(market_profile_url(market_profile))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        market_profile = MarketProfile.create! valid_attributes
        patch market_profile_url(market_profile), params: { market_profile: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested market_profile' do
      market_profile = MarketProfile.create! valid_attributes
      expect do
        delete market_profile_url(market_profile)
      end.to change(MarketProfile, :count).by(-1)
    end

    it 'redirects to the market_profiles list' do
      market_profile = MarketProfile.create! valid_attributes
      delete market_profile_url(market_profile)
      expect(response).to redirect_to(market_profiles_url)
    end
  end
end
